# Generated by Django 4.1.7 on 2023-06-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(choices=[('BA', 'B.A'), ('BSC', 'B.SC'), ('COMMERCE', 'COMMERCE'), ('COMPUTER APPLICATION', 'COMPUTER APPLICATION'), ('BED', 'B.ED')], max_length=20)),
                ('purpose', models.CharField(choices=[('TO VISIT', 'TO VISIT'), ('TO APPLY', 'TO APPLY'), ('TO KNOW', 'TO KNOW')], max_length=20)),
                ('materialsprovided', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'student',
            },
        ),
    ]
